# Generated by Django 4.0.8 on 2022-12-05 09:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordWebhook',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(
                    default='A Discord Webhook', max_length=50)),
                ('discord_webhook', models.TextField()),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PingerIngressConfig',
            fields=[
                ('nickname', models.CharField(
                    default='A Webhook Router', max_length=50)),
                ('identifier', models.UUIDField(
                    default=uuid.uuid4, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('routes', models.ManyToManyField(
                    blank=True, to='rerouter.discordwebhook')),
            ],
        ),
    ]
